# Generated by Django 6.0.4 on 2026-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='data_registro',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
