# Generated by Django 6.0.4 on 2026-04-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_manutencao_data_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='horimetro',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horímetro (h)'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='data_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
