# Generated by Django 6.0.4 on 2026-04-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_manutencao_horimetro_alter_manutencao_data_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='manutencao',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='manutencao.oficina', verbose_name='Oficina'),
        ),
    ]
