# Generated by Django 6.0.4 on 2026-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_oficina_manutencao_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluída'), ('aguardando_orcamento', 'Aguardando Orçamento'), ('orcamento_aprovado', 'Orçamento Aprovado')], default='aguardando_orcamento', max_length=30),
        ),
    ]
