# Generated by Django 6.0.4 on 2026-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0007_equipamento_criado_por_oficina_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data_registro',
            field=models.DateField(verbose_name='Data de Registro'),
        ),
    ]
